name: 'budgeteer-test'
services:
  # Application Test Service
  budgeteer-test:
    container_name: budgeteer-test
    image: seantokuzo/budgeteer-dev
    environment:
      - NODE_ENV=test
      - JWT_SECRET=testJwtSecret
      - JWT_LIFETIME=1d
      - MONGO_URI=mongodb://budgeteer-mongo-test:27017/budgeteer-testdb
      - TEST_COMMAND=${TEST_COMMAND}
    volumes:
      - ./client:/usr/src/app/client
      - ./:/usr/src/app
      - client_test_node_modules:/usr/src/app/client/node_modules
      - server_test_node_modules:/usr/src/app/node_modules
    depends_on:
      - budgeteer-mongo-test
    command: npm run ${TEST_COMMAND}
  # Test Mongo Service
  budgeteer-mongo-test:
    image: mongo
    container_name: budgeteer-mongo-test
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_DATABASE=budgeteer-testdb
    # mute mongo container logs
    command: mongod --quiet --logpath /dev/null

volumes:
  client_test_node_modules:
  server_test_node_modules:
