name: 'budgeteer-dev'
services:
  # APPLICATION DEV SERVICE
  budgeteer-dev:
    container_name: budgeteer-dev
    image: seantokuzo/budgeteer-dev
    ports:
      - 5150:5150
      - 3000:3000
    environment:
      # General env vars
      - NODE_ENV=development
      - PORT=${PORT}
      # Auth env vars
      - JWT_SECRET=${JWT_SECRET}
      - JWT_LIFETIME=${JWT_LIFETIME}
      # Database env vars
      - MONGO_URI=${MONGO_URI}
    volumes:
      - ./client:/usr/src/app/client
      - ./:/usr/src/app
      - client_node_modules:/usr/src/app/client/node_modules
      - server_node_modules:/usr/src/app/node_modules
    depends_on:
      - budgeteer-pg-dev
    command: npm run dev

volumes:
  client_node_modules:
  server_node_modules:
  postgres-dev-volume:
