name: 'budgeteer-dev'
services:
  # APPLICATION DEV SERVICE
  budgeteer-dev:
    container_name: budgeteer-dev
    image: seantokuzo/budgeteer-dev
    ports:
      - 5150:5150
      - 3000:3000
    environment:
      # General env vars
      - NODE_ENV=development
      - PORT=${PORT}
      # Auth env vars
      - JWT_SECRET=${JWT_SECRET}
      - JWT_LIFETIME=${JWT_LIFETIME}
      - JWT_CONFIRM_LIFETIME=${JWT_CONFIRM_LIFETIME}
      # Database env vars
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
    volumes:
      - ./client:/usr/src/app/client
      - ./:/usr/src/app
      - client_node_modules:/usr/src/app/client/node_modules
      - server_node_modules:/usr/src/app/node_modules
    depends_on:
      - budgeteer-pg-dev
    command: npm run dev
  # POSTGRES DEV SERVICE
  budgeteer-pg-dev:
    container_name: budgeteer-pg-dev
    image: postgres:16.3
    # image: seantokuzo/budgeteer-pg-dev
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./scripts/db/postgres/:/docker-entrypoint-initdb.d/
      - postgres-dev-volume:/var/lib/postgresql/data

volumes:
  client_node_modules:
  server_node_modules:
  postgres-dev-volume:
